name: CI

on:
  schedule:
    - cron: '* * * * *'

jobs:
  Auto_Sync:
    runs-on: [ubuntu-latest]
    steps:
      - uses: TG908/fork-sync@v1.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ArunVenkata
          base: master
          head: master
